### ISSUE TITLE
Review documentation enums and monetary fields

### ISSUE THREAD

**Issue by dbeyda** [sdec-brasil/dashboard#42]
In our [wiki](https://github.com/sdec-brasil/dashboard/wiki/Especifica%C3%A7%C3%A3o-da-Nota-Fiscal-de-Servi%C3%A7o-Distribu%C3%ADda) and in our swagger docs, monetary fields are stored as float with two decimal places (we store the R$ quantity). They should be changed to an integer, corresponding to the same total quantity, but stored in cents (R$*100).

Besides that, some Enum fields only have two options: 1 - Yes, 2 - No. When that happens, the field type should be changed to boolean.

**Comment by dbeyda** [comment]
#### Wiki Docs:
- [x] Fixed monetary fields.
- [x] Include the field "estado".
- [x] Review changed field names.
- [x] Fixed boolean fields.

#### Swagger Docs:
- [x] Fixed boolean fields.
- [x] Fixed monetary fields.
- [x] Review changed field names.

#### Database Invoice model:
- [x] Fixed boolean fields.
- [x] Fixed monetary fields.

**Comment by dbeyda** [comment]
@tloriato I have no idea where to put the "estado" field in the Wiki. Which section should it go in? Any suggestions?

**Comment by tloriato** [comment]
@dbeyda Which "estado" ?

**Comment by dbeyda** [comment]
@dbeyda "estado" is an enum holding one of those values: pendente, pago, atrasado, substituido, dados inconsistentes.

**Comment by tloriato** [comment]
"estado" is an status of an invoice, it should be in its table. each invoice has a single "estado"

**Comment by dbeyda** [comment]
Added, all good.
