### ISSUE TITLE
Node Sequelize. TypeError

### ISSUE THREAD

**Issue by tloriato** [sdec-brasil/dashboard#5]
Roda o docker compose, depois da um npm start na API pra ver o erro.

-----------------
https://stackoverflow.com/questions/1827063/mysql-error-key-specification-without-a-key-length/1827099#1827099

https://stackoverflow.com/questions/45755521/node-sequelize-typeerror

**Comment by FranciscoThiesen** [comment]
ok!

**Comment by tloriato** [comment]
nao acho que o erro é o que eu comentei ali não, passei as ultimas 2 horas tentando debugar isso...

tem pelo menos um problema com algum dos modelos nessa lista [abe_lock, abe_seq, chain, chain_candidate, block], pois eu importei só esses 5 e deu ainda o mesmo erro.

eu tava usando essa estrutura e botando e tirando comentario para testar https://raw.githubusercontent.com/sdec-brasil/dashboard/e404f7cd02f8400a74dc7bc30ef39574a38021e8/api/src/models/index.js

**Comment by tloriato** [comment]
Fixed on https://github.com/sdec-brasil/dashboard/commit/22f48d7e992c798d0e6c395c442df8cc658be186
