### ISSUE TITLE
Acho melhor ter as definições de uma tabela num arquivo só, e aí importamos ele sozinho dentro da pasta Blockchain.

### ISSUE THREAD

**Issue by tloriato** [sdec-brasil/dashboard#52]
Acho melhor ter as definições de uma tabela num arquivo só, e aí importamos ele sozinho dentro da pasta Blockchain. 

Temos que saber se podemos começar o servidor carregando o modelo do block ou se vai entrar em conflito com o Worker. Se entrar em conflito tem como você usar o modelo com o Sequelize sem necessariamente usar o Sequelize para criar a tabela.

_Originally posted by @tloriato in https://github.com/sdec-brasil/dashboard/pull/51_

**Comment by tloriato** [comment]
https://github.com/sdec-brasil/dashboard/pull/51#discussion_r293636957

**Comment by dbeyda** [comment]
@tloriato já foi resolvido, podemos fechar?
